// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ3ZV27J8GGHbUlSxKRgER9ZOD-7l7oEI',
    appId: '1:176994865070:web:f541d23555c3628ffb423f',
    messagingSenderId: '176994865070',
    projectId: 'charging-56c76',
    authDomain: 'charging-56c76.firebaseapp.com',
    storageBucket: 'charging-56c76.appspot.com',
    databaseURL: 'https://charging-56c76-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQnFHc1mChwhGGvJ4k5p9-CoBq707D3ug',
    appId: '1:176994865070:android:c52ca9f7f665f56efb423f',
    messagingSenderId: '176994865070',
    projectId: 'charging-56c76',
    storageBucket: 'charging-56c76.appspot.com',
    databaseURL: 'https://charging-56c76-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEj_C0BJff3jZtQeaKxJrg_MMtfe4pNsI',
    appId: '1:176994865070:ios:60a7c004a3c275f1fb423f',
    messagingSenderId: '176994865070',
    projectId: 'charging-56c76',
    storageBucket: 'charging-56c76.appspot.com',
    iosBundleId: 'com.example.appnew',
    databaseURL: 'https://charging-56c76-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEj_C0BJff3jZtQeaKxJrg_MMtfe4pNsI',
    appId: '1:176994865070:ios:60a7c004a3c275f1fb423f',
    messagingSenderId: '176994865070',
    projectId: 'charging-56c76',
    storageBucket: 'charging-56c76.appspot.com',
    iosBundleId: 'com.example.appnew',
    databaseURL: 'https://charging-56c76-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ3ZV27J8GGHbUlSxKRgER9ZOD-7l7oEI',
    appId: '1:176994865070:web:c54ec1861d533647fb423f',
    messagingSenderId: '176994865070',
    projectId: 'charging-56c76',
    authDomain: 'charging-56c76.firebaseapp.com',
    storageBucket: 'charging-56c76.appspot.com',
    databaseURL: 'https://charging-56c76-default-rtdb.firebaseio.com/',
  );
}
